### ISSUE TITLE
Elixir build and watch command

### ISSUE THREAD

**Issue by ThibaudDauce** [LaravelBA/laravel-js-routes#1]
Hi,

Thanks for this amazing package!

> Lazy Tip If you use elixir (or any js task manager), set up a watcher that runs this command whenever your php routes change.

Could you provide an example of an Elixir configuration to build the `routes.js` file with the `gulp` command and to update it with the `gulp watch`?

I found this online but do you know an easier way? http://stackoverflow.com/questions/28569604/laravel-elixir-execute-cmd-on-watch-update

Thanks a lot!

**Comment by fedeisas** [comment]
Hi @ThibaudDauce! Have you tried the solution you've found yet?

The `gulp-shell` plugin actually has a (`cwd` option)[https://www.npmjs.com/package/gulp-shell#optionscwd] so you could do something like:

```js

```
